Add Application to datasource configuration
grafana/azure-data-explorer-datasource pull request #1107
Opened 2024-11-29 07:11 UTC by benmali

Added 'Application' option to Datasource config instead of hardcoded 'Grafana-ADX'

2024-11-29 07:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/azure-data-explorer-datasource?pullRequest=1107) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/azure-data-explorer-datasource?pullRequest=1107) before we can accept your contribution.<br/><hr/>**Ben Mali** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/azure-data-explorer-datasource?pullRequest=1107) it.</sub>

2024-11-29 11:21 UTC, aangelisc requested changes
Hi @benmali, thank you for the PR. Just to clarify - is the purpose of this for tracking in ADX?

Additionally, it seems like you need to merge main as this PR is reverting some recent changes.

2024-12-08 08:05 UTC, benmali commented
Another use case I'm interested in is using Workload Groups by 'Application'. This will give us the ability to limit resources for heavy dashboard queries that are not production critical. https://learn.microsoft.com/en-us/kusto/management/workload-groups?view=microsoft-fabric#use-cases-for-custom-workload-groups

2025-01-05 17:49 UTC, benmali commented
Hi @aangelisc, is there anything I can do on my side do push this? This is a feature we really want

2025-01-14 09:17 UTC, taleena commented
@benmali it looks like you still need to signed the CLA, and I suspect you need to update the PR as Andreas mentioned earlier if you haven't already. For the other use case you mentioned, would you mind putting in an issue feature request?

2025-01-16 18:04 UTC, benmali commented
Hi, CLA signed. No need for a feature request regarding the workload groups in the meantime.

2025-01-16 22:21 UTC, adamyeats commented
@benmali I've run the CI (unfortunately we have to approve builds from external contributors, which is why it was pending) but it is currently failing the lint step, could you check the output and resolve the errors?

2025-01-17 17:07 UTC, benmali commented
@adamyeats Should be fixed now.

2025-01-20 18:39 UTC, benmali commented
@adamyeats I see that I missed one function def. Hope it is fixed now

2025-01-20 20:58 UTC, benmali commented
@adamyeats I see that the CI is failing beacause of missing `libasound2` package.

I can see here https://launchpad.net/ubuntu/jammy/+package/libasound2 that this is an ubuntu 22.04 package, while the runner you are using is ubuntu-latest runner image, which is ubuntu 24.04 as described here: https://github.com/actions/runner-images

I'm guessing changing the runner to ubuntu-22.04 in the failing steps will solve this.

Also, discussed in this issue.
https://github.com/microsoft/playwright/issues/30368

2025-01-21 15:52 UTC, adamyeats commented
@benmali Apologies for the difficulties here! I think one more rebase from `main` should be enough to get us over the tine here. Thanks for your patience!

2025-01-21 18:42 UTC, benmali commented
@adamyeats Done

2025-01-21 19:27 UTC, adamyeats approved these changes
Thanks @benmali, LGTM!

2025-01-21 19:31 UTC, adamyeats submitted a review, later dismissed

2025-01-23 12:58 UTC, adamyeats commented
@benmali My approval was dismissed on this PR, is there something you wanted to change?

2025-01-23 13:15 UTC, benmali commented
@adamyeats No, I didn't do anything on my end. I have no idea why was the approval dismissed

2025-01-23 14:15 UTC, adamyeats approved these changes

2025-01-23 15:47 UTC, aangelisc approved these changes

2025-01-23 15:48 UTC, adamyeats approved these changes

2025-01-23 15:48 UTC, merged