Enhancement: Support National Clouds
grafana/azure-data-explorer-datasource pull request #217
Opened 2021-03-17 15:58 UTC by joshhunt

Closes #16

Adds support for the Azure US Gov (Fairfax) and China (Mooncake) national clouds.

Need to do a bit of light smoke tests first before testing in the other clouds.

2021-05-10 12:15 UTC, sunker approved these changes
Looks good, but we need to find a way of solving this for already configured data sources.

2021-05-10 12:15 UTC, sunker requested changes
Looks good, but we need to find a way of solving this for already configured data sources.

2021-05-10 12:43 UTC, sunker commented on src/plugin.json
> +        "url": "{{.JsonData.nationalCloud}}/{{.JsonData.tenantId}}/oauth2/token",
Yeah. Don't think there's any simple solution to this unfortunately. One path forward though would be to skip the reverse proxy in grafana core and implement CallResourceHandler and handle auth there instead. This is kind of explained [here](https://github.com/grafana/grafana/issues/33809).

2021-05-10 14:20 UTC, joshhunt commented on src/plugin.json
> +        "url": "{{.JsonData.nationalCloud}}/{{.JsonData.tenantId}}/oauth2/token",
oh i was hoping there were the hooks to override the URL in the ADX backend code. sad face

2021-05-12 15:44 UTC, floushee commented on src/plugin.json
> +        "url": "{{.JsonData.nationalCloud}}/{{.JsonData.tenantId}}/oauth2/token",
Would it be an option to use https://login.microsoftonline.com per default as a fallback? Then there should not be any issues with already configured data sources?

2021-05-25 06:03 UTC, floushee commented on src/plugin.json
> +        "url": "{{.JsonData.nationalCloud}}/{{.JsonData.tenantId}}/oauth2/token",
How did they make it work in the https://github.com/grafana/azure-monitor-datasource data source?

2021-05-31 15:24 UTC, closed without merging