Add anonymous authentication capability
grafana/azure-data-explorer-datasource pull request #590
Opened 2023-06-09 21:29 UTC by mikeycham

Microsoft recently released the [Azure Data Explorer Kusto emulator](https://learn.microsoft.com/en-gb/azure/data-explorer/kusto-emulator-overview), which allows you to create a local cluster for local development. The emulator, however, [does not support any type of Azure AD authentication](https://learn.microsoft.com/en-gb/azure/data-explorer/kusto-emulator-install#connect-to-the-emulator), and therefore must be connected to anonymously without any of the usual Azure AD headers. 

This pull request adds the option for anonymous authentication to be configured via the UI, and if selected will remove all Azure AD middleware from the go HTTP client. 

Thanks!

2023-06-09 21:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/azure-data-explorer-datasource?pullRequest=590) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/azure-data-explorer-datasource?pullRequest=590) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/azure-data-explorer-datasource?pullRequest=590) it.</sub>

2023-06-13 19:11 UTC, asimpson requested changes
This looks solid to me :trophy: 

Could you possibly include a short-write up in `doc` directory that explains what "anonymous" auth is and why someone would use it?

2023-06-13 19:11 UTC, asimpson commented on src/tracking.ts
> +  anonymous_queries: number;
Love the update to tracking :trophy:

2023-06-14 08:59 UTC, aangelisc requested changes
Thank you for the submission @mikeycham! The frontend changes look fine to me (thank you for including the tracking update). However, we're trying to ensure the logic for credentials is unified in the `grafana-azure-sdk-go` package (see [here](https://github.com/grafana/grafana-azure-sdk-go/blob/6112a9b5a1a5390a9aa6123d86d5429c39757c37/azcredentials/builder.go#L19)). Take a look at this and let me know if you'd be able to move the changes to that package 😊

2023-07-05 09:16 UTC, aangelisc commented
Hi @mikeycham are you able to make these changes to the SDK?

2023-07-11 10:45 UTC, mikeycham commented
Hi @aangelisc, apologies for the long delay - that's no problem, I should have some time this week to make the required changes to the SDK.

2023-08-09 15:04 UTC, aangelisc commented
I'm going to close this in favour of moving the required changes to the SDK soon 😊

2023-08-09 15:04 UTC, closed without merging